apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-gitops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-gitops-app
  template:
    metadata:
      labels:
        app: python-gitops-app
    spec:
      containers:
        - name: python-gitops-app
          image: ghcr.io/betkibet/devops-playbook:8c1ebbd86bd60355a8c4e6b48d7e505089a4ef1d
          ports:
            - containerPort: 8000