apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-gitops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-gitops-app
  template:
    metadata:
      labels:
        app: python-gitops-app
    spec:
      containers:
        - name: python-gitops-app
          image: ghcr.io/betkibet/devops-playbook:4c723ffb58db901164b2963e825cb71cb3b1c47a
          ports:
            - containerPort: 8000